apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: kostikorhonen/back:latest
          #readinessProbe:
          #  initialDelaySeconds: 10
          #  periodSeconds: 5
          #  httpGet:
          #    path: /healthz
          #    port: 3001
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            httpGet:
              path: /healthz
              port: 3001
          resources:
            limits:
              cpu: "100m"
              memory: "150Mi"
          envFrom:
            - secretRef:
                name: dbpw
          env:
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: dbpw
                  key: POSTGRES_PASSWORD
            - name: DBUSER
              value: "postgres"
            - name: DBHOST
              value: "postgres-svc"
            - name: DBDB
              value: "postgres"
            - name: DBPORT
              value: "5432"