apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: log-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ping-pong-dep
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50