apiVersion: apps/v1
kind: Deployment
metadata:
  name: project03-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project03
  template:
    metadata:
      labels:
        app: project03
    spec:
      containers:
        - name: project03
          image: kostikorhonen/project01:latest