apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-rate
spec:
  metrics:
  - name: cpu-usage
    interval: 10s
    successCondition: result < 0.5
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1657-prometheus.prometheus.svc:9090 # DNS name for my Prometheus, find yours with kubectl describe svc ...
        query: |
          scalar(
            sum(rate(node_cpu_seconds_total{mode!="idle", namespace="master"}[5m]))/sum(machine_cpu_cores)
          )*100